### ISSUE TITLE
Use real URL

### ISSUE THREAD

**Issue by olexandr-konovalov** [sebasguts/MetaPackage#1]
The PackageInfo.g file in gh-pages should be exactly like in the package, so should have real URL here:
https://github.com/sebasguts/MetaPackage/blob/c42b930f25cd9e190b009640bd1af97190308b67/PackageInfo.g#L36

Otherwise, packages update trips over at
```
Package: Metapackage
# Error (/circa/home/gap-jenkins/pkgadmin/pkgcache/metapackage/tmp/tmpinfo.g):\
 no package info bound!
  WARNING (Metapackage): no success in download of the current info file 
  from http://TODO/PackageInfo.g
```

**Comment by sebasguts** [comment]
Sry, I am stupid. Will fix this.
